language: generic

sudo: false
dist: bionic

branches:
  only:
  - master

matrix:
  include:
  - name: "Python 3.8 - linux"
    env: PYTHON_VERSION=3.8
    os: linux
  - name: "Python 3.9 - linux"
    env: PYTHON_VERSION=3.9
    os: linux
  - name: "Python 3.10 - linux"
    env: PYTHON_VERSION=3.10
    os: linux
  - name: "Lint"
    env: PYTHON_VERSION=3.8
    os: linux
    script:
    - pip install black==19.10b0
    - black . --diff --check

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      OS=Linux ;
  else
      OS=MacOSX ;
  fi ;
  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$OS-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda;
- export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH";
- conda config --set always_yes yes --set changeps1 no;
- conda env create -f environment.yml
- source ~/miniconda/bin/activate cadquery
- conda install -c conda-forge -c defaults -c cadquery python=$PYTHON_VERSION
- conda install -c conda-forge -c cadquery cadquery=master

install:
- python setup.py install

script:
- cd tests
- pytest -v --cov

after_success:
- codecov
