name: cadquery
channels:
  - cadquery
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - ipython
  - numpy=1.23
  - ocp>=7.6.*
  - pyparsing>=2.1.9
  - sphinx=5.0.1
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - black=19.10b0
  - codecov
  - click=8.0.4
  - pytest
  - pytest-cov
  - ezdxf
  - ipython
  - typing_extensions
  - nptyping=2.0.1
  - pip
  - pip:
    - "--editable=."
    - sphinxcadquery
    - multimethod>=1.7,<2.0
